# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.version.version

'1.16.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
null=np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [16]:
print('%d bytes'% (null.size*null.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [60]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.  If ``x1.shape != x2.shape``, they must be\n    broadcastable to a common shape (which may be the shape of one or\n    the other).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or `None`,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    Values of True indicate to calculate the ufunc at that position, values\n    of False indicate to leave the value in the output alone.\n**kwargs\n    For other keyword-only arguments, see the\n    :ref:`ufunc docs <ufuncs.kwargs>`.\n\nReturns\n-------\nadd : 

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
null[5]=1
null

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [29]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [30]:
vector=np.flipud(vector)
vector


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [42]:
nonzero=np.nonzero([1,2,0,0,4,0])
nonzero

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [43]:
identity=np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
random=np.random.random((3,3,3))
random

array([[[0.66078872, 0.21184089, 0.27037443],
        [0.4245576 , 0.28664931, 0.94099681],
        [0.26727489, 0.99269505, 0.232825  ]],

       [[0.4133771 , 0.8505837 , 0.46769474],
        [0.24282035, 0.39271305, 0.63414   ],
        [0.38480271, 0.41719561, 0.83511178]],

       [[0.41301176, 0.82663945, 0.20556897],
        [0.38200993, 0.62679386, 0.36108575],
        [0.08419055, 0.3197342 , 0.70872136]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [52]:
random=np.random.random((10,10))
min=np.min(random)
print(min)
max=np.max(random)
print(max)

0.012650814972200775
0.998382396071417


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [53]:
random=np.random.random(30)
mean=np.mean(random)
print(mean)

0.45758857981585443


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [63]:
random=np.ones((6,5))
random[1:-1,1:-1]=0
random

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [77]:
random=np.ones((7,5))
random=np.pad(random, pad_width=1, mode='constant', constant_values=0)
random


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [82]:
dia=np.diag(1+np.arange(4),k=-1)
dia

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [84]:
check=np.zeros((8,8),dtype=int)
check[1::2,::2]=1
check[::2,1::2]=1
check

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [131]:
index=np.unravel_index(99,(6,7,8))
index

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [139]:
np.tile(check,1)


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [148]:
norm=np.random.random((5,5))
norm1=(norm-np.mean(norm))/np.std(norm)
norm1

array([[-0.84830261, -1.52565982,  1.93944462, -0.0515818 ,  1.32959748],
       [-0.77204391,  0.18762952,  0.65720408, -0.51114517, -0.17327852],
       [ 2.14122051,  0.7540139 , -1.36979451, -0.97076351, -0.07148082],
       [-1.00550071, -1.03637763, -0.62533692,  0.55897219,  0.56115651],
       [ 1.3420052 , -0.53113881,  0.72188291, -1.10399887,  0.40327668]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

array([0, 1, 2, 3, 4])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [160]:
mul=np.random.random((5,3))

mul1=np.random.random((3,2))
mul2=mul.dot(mul1)
print(mul2)


[[0.27635159 0.16628084]
 [0.54906137 0.28851398]
 [1.5281368  0.81219215]
 [1.37279507 0.63618034]
 [1.51787996 0.75559525]]


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [169]:
negate=np.arange(10)
negate[(negate>3)&(negate<8)]*=-1
negate

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [173]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z<z>z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [1]:
import numpy as np

In [6]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [11]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [23]:
n1=np.random.randint(0,10,5)
n2=np.random.randint(1,8,4)
np.intersect1d(n1,n2)

array([1, 2])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [24]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-24-cb59a649a670>, line 7)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [27]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Venky\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today     = np.datetime64('today', 'D')
print(today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2019-09-04
2019-09-05
2019-09-04 2019-09-05 2019-09-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [39]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
add=np.add(A,B,out=B)
Div=np.divide(A,2,out=A)
Ne=np.negative(Div,out=Div)
mul=np.multiply(add,Ne)
mul

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [53]:
z=np.random.uniform(0,10,10)
z1=z-z%1
print(z1)
floor=np.floor(z)
print(floor)
ceil=np.ceil(z)-1
print(ceil)
print(np.trunc(z))


[3. 0. 9. 4. 7. 3. 3. 3. 4. 9.]
[3. 0. 9. 4. 7. 3. 3. 3. 4. 9.]
[3. 0. 9. 4. 7. 3. 3. 3. 4. 9.]
[3. 0. 9. 4. 7. 3. 3. 3. 4. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [63]:
row=np.zeros((5,5))
row+=np.arange(5)
row

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [73]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [85]:
a=np.random.random(10)
np.sort(a)

array([0.16251741, 0.33791445, 0.33901335, 0.52075339, 0.65175886,
       0.68444597, 0.89440639, 0.92278778, 0.93989724, 0.96064237])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [100]:
small=np.arange(5)
a=np.add.reduce(small)
print(a)
    

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [196]:
a=np.random.random((0,2,9))
b=np.random.random((0,2,2))
equal=np.array_equal(a,b)
print(equal)

[]
[]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [111]:
z=np.ones((3))
z.flags.writeable=True
z[2]=3
z

array([1., 1., 3.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [125]:
z=np.random.random((10,2))
x,y=z[:,0], z[:,1]
r=np.sqrt(x**2+y**2)
theta=np.arctan2(y,x)
print(theta)
sin=r*np.sin(theta)
print(sin)
cos=r*np.cos(theta)
print(cos)

[1.39121457 0.30760655 0.80246228 0.81266013 0.87741459 0.57257943
 0.25381255 1.2923809  0.13939427 1.18006456]
[0.65857859 0.25554989 0.62211615 0.95205545 0.87055781 0.25032727
 0.2421427  0.1511239  0.11847718 0.56609836]
[0.11955669 0.80439896 0.60123865 0.90151105 0.72346605 0.38833684
 0.93344696 0.04319718 0.84443085 0.23318191]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [127]:
n=np.arange(10)
n[np.max(n)]=0
print(n)

[0 1 2 3 4 5 6 7 8 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [133]:
grid=np.zeros((5,5), [('x',float),('y',float)])
grid['x'],grid['y']=np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(grid)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [150]:
x=np.arange(5)
y=x+0.5
z=1.0/np.subtract.outer(x,y)
cauchy=np.linalg.det(z)
print(cauchy)

-131.91659501325745


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [154]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtpe in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


ValueError: data type <class 'numpy.int64'> not inexact

#### 49. How to print all the values of an array? (★★☆)

In [180]:
np.set_printoptions(threshold=np.nan)
z=np.zeros((10,10))
print(z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [206]:
x=np.arange(100)
y=np.random.random((1,100))
z=(np.abs(x-y)).argmin()
z

1

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)